name: Edge version Build

on: 
  push:
    branches:    
      - master

jobs:
  publish-to-docker-io:
    name: Publish edge to Docker.io
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jerray/publish-docker-action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: fspnetwork/nginx
        cache: fspnetwork/nginx
        tags: edge