name: Docker Build

on:
  push:
    tags:
      - '1*' # Push events to matching v*, i.e. 1.0, 20.15.10

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Release for Tag
        id: release_tag
        uses: yyx990803/release-tag@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          body: |
            Please refer to [CHANGELOG.md](https://github.com/FSPNET/Nginx/blob/master/CHANGELOG.md) for details.

  publish-to-docker-io:
    name: Publish to Docker.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: fspnetwork/nginx
          cache: fspnetwork/nginx
          auto_tag: true
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: fspnetwork/nginx
          cache: fspnetwork/nginx
          tags: latest